# Generated by Django 5.0.6 on 2024-05-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubSpotCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(default='4aa2e97b-86f2-4530-b095-e9b41f90925e', max_length=255)),
                ('client_secret', models.CharField(default='53022830-95d1-41cf-8f81-e5f23aa74ca8', max_length=255)),
                ('access_token', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
    ]
