# Generated by Django 5.0.6 on 2024-05-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_oauthcredentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='APICallResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('response_data', models.TextField()),
                ('status_code', models.IntegerField()),
                ('successful', models.BooleanField(default=False)),
            ],
        ),
    ]
