# Generated by Django 5.0.6 on 2024-05-14 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_apicallresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HubSpotCredentials',
        ),
    ]
